#+TITLE:Org-Mode Integration for Elfeed
#+AUTHOR: Steven Allen

Configure [[https://github.com/emacs-elfeed/elfeed][Elfeed]] feeds with org-mode files. This package parses one or more org-mode documents and populates ~elfeed-feeds~ based on the contents of these documents.

This package was heavily inspired by [[https://github.com/remyhonig/elfeed-org][@remyhonig's elfeed-org]].

* Usage
:PROPERTIES:
:ID:       af260ac0-414d-4da6-91e2-ac515413f329
:END:

To use ~elfeed-org~, you need to install it (after installing Elfeed itself), configure your ~elfeed-org-files~, and enable ~elfeed-org-mode~. If you use ~use-package~, I suggest starting with the following:

#+begin_src elisp
(use-package elfeed-org
  :vc (:url "https://github.com/Stebalien/elfeed-org")
  :after elfeed
  :custom
  ;; This must be a list of org-mode files where you put your feeds.
  ;;
  ;; - Relative file paths are resolved relative to to `org-directory'
  ;;   (defaults to "~/org").
  ;; - This list starts out empty, you MUST configure it if you want `elfeed-org'
  ;;   to do anything.
  (elfeed-org-files '("feeds.org"))
  ;; This package won't do anything until you turn on its minor mode.
  (elfeed-org-mode t))
#+end_src

This package is not available on any package repository (MELPA, ELPA, etc.) at the moment.

** Configuration
:PROPERTIES:
:ID:       77db31e8-133c-4e0d-b053-4d09bb19d592
:END:

This package is configured with an org-mode file where each headline is a feed.

#+begin_src org
,* My Feeds :elfeed:
  Due to tag inheritence, everything in this tree will be tagged with ~:elfeed:~
  and will be added to your ~elfeed-feeds~ list.
  ,** [[https://planet.emacslife.com/atom.xml][Planet Emacslife]] :emacs:
    This is Sacha Chua's "Emacs Planet", an aggregation of many Emacs blogs
    into a single feed. This description is just for you, ~elfeed-org~ will
    ignore it.
  ,** [[https://www.eff.org/rss/updates.xml][EFF]] :politics:
    This title of this blog is actually "Deeplinks". However, because I've used
    "EFF" as the org-mode link description, the feed's title will be changed to
    "EFF".
  ,** [[https://www.phoronix.com/rss.php][Phoronix]] :linux:
    :PROPERTIES:
    :ELFEED:READABLE: t
    :ELFEED:FETCH-LINK: replace
    :END:
    Feeds headlines may specify elfeed feed properties.
  ,** Personal Blogs :blog:
    I subscribe to a few personal blogs and I put them all within this subtree. Due
    to tag inheritence, all entries from these blogs will be tagged with ~blog~.
    ,*** https://nesbitt.io/feed.xml :technology:
      Feeds lacking descriptions (bare URLs) will use the title from the feed itself.
  ,** Ignored
    This package provides a few ways to ignore feeds.
    ,*** COMMENT [[https://this-week-in-rust.org/atom.xml][This Week in Rust]] :rust:
      This feed is "commented out", so it won't show up in elfeed.
    ,*** [[https://matrix.org/blog/feed][matrix.org]] :ARCHIVE:
      The same rule applies to archived feeds.
    ,*** [[https://planet.kernel.org/rss20.xml][Kernel Planet]] :linux:ignore:
      Feeds with the ~:ignore:~ tag are ignored as well.
,* Inbox
  This is where I capture my new feeds. They aren't tagged with ~:elfeed:~, so
  they won't actually show up in elfeed until I refile them into the appropriate
  section above.
  ,** [[https://lars.ingebrigtsen.no/feed/][Lars Ingebrigtsen]] :emacs:
#+end_src

Configured feeds will automatically be synced to ~elfeed-feeds~ when you save any file listed in ~elfeed-org-files~, enable/disable ~elfeed-org-mode~, or modify ~elfeed-org-files~.

** Org Capture
:PROPERTIES:
:ID:       26497301-ae97-4463-9831-6e4885547227
:END:

While you can add new entries to your org-based feed list, I highly recommend configuring org-capture to make this easier.

First, you'll need to configure [[https://orgmode.org/worg/org-contrib/org-protocol.html][org-protocol]] and integrate it into your web browser (I use and wrote [[https://github.com/Stebalien/org-capture-extension][org-capture-extension]], but this isn't the only option).

Then you'll need to add an org-capture template. You'll need to modify the following to put your captured feeds in the right place. See the [[https://orgmode.org/manual/Capture-templates.html][capture template documentation]] for more details.

#+begin_src elisp
(push `("f" "Feed" entry (file+olp "feeds.org" "Inbox") ,elfeed-org-capture-template))
#+end_src

Where ~elfeed-org-capture-template~ is defined as:

#+begin_src org
,* %(elfeed-org-capture:annotation)
:PROPERTIES:
:CREATED: %U
:SOURCE: %:annotation
:END:
#+end_src

When you capture a link with this template, Emacs will:

1. Extract any feeds referenced in the captured link.
2. Ask you which feed you want to subscribe to if there's more than one.
3. Prompt you for a feed title.
4. Present a captured org-mode entry suitable for inclusion in your "feeds.org" file.

* Comparison
:PROPERTIES:
:ID:       c6f88dd6-40a7-49bd-9918-2cb35953e64c
:END:

Compared to [[https://github.com/remyhonig/elfeed-org][@remyhonig's]] elfeed-org, this package:

1. Auto-updates ~elfeed-feeds~ whenever any file listed in ~elfeed-org-files~ changes (without having to close and re-open elfeed).
2. Extends ~elfeed-feeds~ instead of replacing it in case you want to configure feeds from multiple sources (e.g., OPML files).
3. Avoids advising elfeed functions and instead relies on hooks.
4. Supports setting elfeed feed properties (readable, fetch, etc.).

However, it doesn't implement the following features:

1. Title-based tagging rules (=entry-title: REGEX=). I may implement a comprable feature eventually, but it'll likely use org-babel instead of regular expressions in headlines.
2. Auto-ignoring broken feeds. I have no plans to implement this.
3. OPML Import/Export. This would be a "nice to have" for new users, but it's not something I'm likely going to tackle any time soon.

* Copyright & Acknowledgements
:PROPERTIES:
:ID:       28eae0c7-4b1f-4e89-8974-329612eb3202
:END:

This project is copyright Steven Allen (except as noted below) and licenced under the GPLv3 or any later version.

- The idea for ~elfeed-org~ was graciously plundered from [[https://github.com/remyhonig/elfeed-org][@remyhonig's elfeed-org]], but no code was taken.
- The feed discovery code in ~elfeed-org-capture~ was initially taken from [[https://github.com/HKey/feed-discovery][@HKey's feed-discovery]] package, then largely rewritten to fix some bugs and remove the dependency on ~dash~. As right now, the only remaining function from HKey's project is ~elfeed-org-capture--feed-link-p~.
